Logic Challenge evamp
Justice-Through-Code/spring_2021 pull request #6
Opened 2021-01-29 05:05 UTC by s-ruby

- Re-order exercises so compile time (syntax) errors appear on top.
- Add assert statements and added comments to clarify exactly how logical
bugs should be solved. 
- Added variable value to print statements for readability 
- The program will stop at each exercise until
the bug is fixed.
- Updated `logic_challenge.md` with explanation about syntax versus assertion errors
- Updated solutions file to reflect changes to challenge

2021-02-03 00:28 UTC, pab2163 reviewed
This looks great! Definitely much clearer than before, and nice job with the design so if done in order, the cmd line printout should be informative to the problem students are working on.

Notes:
- I'm still a little unsure of whether incorporating assertions here is a good idea -- let's check in about this and make a decision. 
- Can you make it clear in both the markdown/challenge script that students should make sure they correct each snippet in order? I think most will do this anyway, but just in case. 
-See below for a few line edits

2021-02-03 00:28 UTC, pab2163 commented on challenges/06_bootcamp_logic/logic_challenge_3.md
> +* Syntax errors means the program cannot compile.
I'm not sure if mentioning compiling will be helpful or would just confuse students more. My instinct might be to just leave this out for now?

2021-02-03 00:28 UTC, pab2163 commented on challenges/06_bootcamp_logic/logic_challenge_3.md
> +* `assert()` is a way to test if a condition in your code returns `True`.
@ashiq-r31 I could go either way on the assertions, what do you think? If we have assertions in the challenge, my instinct would be to mention them in the lesson as well.

2021-02-03 00:28 UTC, pab2163 commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +print (f"The value of o ({o}) is True since Python is case-insensitive.")
I don't want to accidentally confuse students into thinking python actually IS case-insensitive here. Is there a way we can better scaffold thinking about case sensitivity?

2021-02-03 00:28 UTC, pab2163 commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +d = ((5 > 7) or not (8 < 20) or True)
this example with two separate `or` statements might trip students up. maybe we could simplify this to just one

2021-02-03 00:28 UTC, pab2163 commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +print("TO DO: Explain how d is set to False")
```suggestion
# TO DO: Explain how d is set to False
```

2021-02-03 00:31 UTC, pab2163 commented
Sorry, I didn't answer question 1. Since this is one of the first times students will be responsible for debugging code someone else wrote, I think it will be challenging enough, even if the bugs seem very 'easy'/explicit

2021-02-03 00:52 UTC, ashiq-r31 commented on challenges/06_bootcamp_logic/logic_challenge_3.md
> +* Syntax errors means the program cannot compile.
Yeah simplistic language like "cannot run" might be better here

2021-02-03 00:54 UTC, ashiq-r31 commented on challenges/06_bootcamp_logic/logic_challenge_3.md
> +* `assert()` is a way to test if a condition in your code returns `True`.
@pab2163 I think we could include `assert` in the lecture. The concept is simple enough and we can demonstrate what assert does and leave it at that.

2021-02-03 00:55 UTC, ashiq-r31 commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +d = ((5 > 7) or not (8 < 20) or True)
@pab2163 agreed

2021-02-03 00:59 UTC, ashiq-r31 commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +print (f"The value of o ({o}) is True since Python is case-insensitive.")
yeah I'd leave this as "case-sensitive"

2021-02-03 01:00 UTC, ashiq-r31 requested changes
Awesome stuff. Adding `assert` was a nice touch.

2021-02-03 01:21 UTC, pab2163 commented
Great! Just following up -- the plan will be to keep the assertions, and I will update the lecture right before this with a demonstration for what `assert()` does

2021-02-03 17:29 UTC, s-ruby commented on challenges/06_bootcamp_logic/snippets_challenge.py
> +d = ((5 > 7) or not (8 < 20) or True)
done!

2021-02-03 17:29 UTC, s-ruby commented on challenges/06_bootcamp_logic/logic_challenge_3.md
> +* Syntax errors means the program cannot compile.
done!

2021-02-03 23:59 UTC, pab2163 approved these changes
thanks, looks great to me!

2021-02-04 01:14 UTC, ashiq-r31 approved these changes
👍 good stuff

2021-02-04 01:15 UTC, merged